<?php

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

function fibo(): int
{
    $firstNumber = 1;
    $secondNumber = 2;

    $sum = 0;
    for ($i = 0;; $i++) {
        if($secondNumber%2==0){
            $sum +=$secondNumber;
        }
        $thirdNumber = $firstNumber + $secondNumber;
        $firstNumber = $secondNumber;
        $secondNumber = $thirdNumber;
        if($thirdNumber>=4000000){
            break;
        }
    }
    return $sum;
}

var_dump(fibo());
